# Generated by Django 4.2.1 on 2024-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_address', models.TextField(max_length=20)),
                ('p_area', models.CharField(max_length=20)),
                ('p_type', models.CharField(choices=[('BUNGLOW', 'BUNGLOW'), ('ROW_HOUSE', 'ROW_HOUSE'), ('APPARTMENT', 'APPARTMENT')], default='APPARTMENT', max_length=15)),
                ('p_furnishingtype', models.CharField(choices=[('fully', 'fully'), ('semi', 'semi'), ('not', 'not')], default='not', max_length=20)),
                ('p_age', models.PositiveIntegerField()),
                ('p_direction', models.CharField(choices=[('north', 'north'), ('south', 'south'), ('east', 'east'), ('west', 'west')], max_length=20)),
                ('p_rentprize', models.PositiveIntegerField()),
                ('p_image', models.ImageField(upload_to='p_images')),
                ('a_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=10)),
                ('password1', models.CharField(max_length=15)),
                ('password2', models.CharField(max_length=15)),
            ],
        ),
    ]
