# Generated by Django 4.2.1 on 2024-01-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='p_image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='p_images')),
                ('proty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealerapp.property')),
            ],
        ),
    ]
