# Generated by Django 4.2.1 on 2024-01-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0002_remove_property_p_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_furnishingtype',
            field=models.CharField(choices=[('FULLY', 'FULLY'), ('SEMI', 'SEMI'), ('NOT', 'NOT')], default='NOT', max_length=20),
        ),
    ]
