# Generated by Django 4.2.1 on 2024-01-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0003_alter_property_p_furnishingtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='p_image',
            field=models.ImageField(upload_to='media/p_images'),
        ),
    ]
