# Generated by Django 4.2.1 on 2024-01-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0004_alter_image_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='p_age',
            field=models.PositiveIntegerField(choices=[('month', 'month'), ('year', 'year')], default='month'),
        ),
    ]
