# Generated by Django 4.2.1 on 2024-01-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealerapp', '0005_alter_property_p_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='p_age_type',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], default='month', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='p_age',
            field=models.PositiveIntegerField(),
        ),
    ]
